site_name: Documentation
site_description: Open source documentation about IT tools and other stuff
site_author: arthurmauvezin

repo_name: arthurmauvezin/wiki
repo_url: https://github.com/arthurmauvezin/wiki

docs_dir: 'docs'

theme:
  name: material
  language: en
  #include_sidebar: true
  favicon: assets/images/wikipedia.icon.png
  palette:
    primary: orange
    accent: deep orange
  features:
    - tabs
  icon:
    logo: fontawesome/brands/wikipedia-w

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/arthurmauvezin
    - icon: fontawesome/brands/twitter-square
      link: https://twitter.com/arthurmauvezin
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/arthurmauvezin

google_analytics:
  - UA-XXXXXXXX-X
  - auto

markdown_extensions:
  - admonition        # Warning, info boxes
  - codehilite        # Color in snippet, line number, highlight line
  - toc:             # Add anchor to all titles 
      permalink: true
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search # necessary for search to work
    #- awesome-pages

nav:
  - Home: index.md
  - Agility:
    - 'Tools': 'agility/tools.md'
  - Azure:
    - 'CLI': 'azure/azure.md'
  - Bash:
    - 'Scripting': 'bash/scripting.md'
    - 'CLI Shortcuts': 'bash/command_line_shortcut.md'
  - Database:
    - 'Postgres': 'database/postgres.md'
  - Docker:
    - 'Setup': 'docker/setup.md'
    - 'Debug': 'docker/debug.md'
    - 'CLI': 'docker/command.md'
    - 'docker-compose': 'docker/compose.md'
    - 'Dockerfile': 'docker/dockerfile.md'
    - 'Template': 'docker/template.md'
  - Fedora:
    - 'System & Network': 'fedora/sysnet.md'
    - 'Fix': 'fedora/fix.md'
    - 'Setup': 'fedora/setup.md'
  - Git: 
    - 'Useful': 'git/git.md'
  - Interview:
    - 'Question': 'interview/personal.md'
    - 'System Administration': 'interview/sysadmin.md'
  - Jenkins:
    - 'Jenkinsfile': 'jenkins/jenkinsfile.md'
    - 'Libs': 'jenkins/lib.md'
  - Kubernetes:
    - 'Kubernetes': 'kubernetes/kubernetes.md'
  - Network:
    - 'Network': 'network/network.md'
    - 'tcpdump': 'network/tcpdump.md'
  - Presentation: 
    - 'Tools': 'presentation/presentation.md'
  - Python:
    - 'Python': 'python/python.md'
  - System:
    - 'System': 'system/system.md'
    - 'Crontab': 'system/cron.md'
  - Vim:
    - 'Useful': 'vim/vim.md'
    - 'IDE': 'vim/ide.md'
    - 'Cheatsheet': 'vim/cheatsheet.md'
