site_name: Documentation
site_description: Open source documentation about IT tools and other stuff
site_author: arthurmauvezin
site_url: https://wiki.autopdutop.fr/
site_description: >-
  Create a branded static site from a set of Markdown files to host the
  documentation of your Open Source or commercial project – customizable,
  searchable, mobile-friendly, 40+ languages

repo_name: arthurmauvezin/wiki
repo_url: https://github.com/arthurmauvezin/wiki

copyright: Copyright &copy; 2015 - 2021 Arthur Mauvezin

docs_dir: 'docs'

theme:
  name: material
  language: en
  #include_sidebar: true
  favicon: assets/images/wikipedia.icon.png
  palette:
    primary: orange
    accent: deep orange
  features:
    - navigation.tabs
  icon:
    logo: fontawesome/brands/wikipedia-w

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/arthurmauvezin
    - icon: fontawesome/brands/twitter-square
      link: https://twitter.com/arthurmauvezin
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/arthurmauvezin

google_analytics:
  - UA-XXXXXXXX-X
  - auto

markdown_extensions:
  - admonition        # Warning, info boxes
  - codehilite        # Color in snippet, line number, highlight line
  - toc:             # Add anchor to all titles 
      permalink: true
  - pymdownx.details # Add collapsible elements
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink # Auto create clickable links
  - pymdownx.superfences # Allow to nest fences (code blocks) into anything. Also use UML directly
  - pymdownx.tabbed # Create tab structure
  - pymdownx.tasklist: # Create task list with already checked items
      custom_checkbox: true

plugins:
  - search # necessary for search to work
    #- awesome-pages

nav:
  - 'Home': 'index.md'
  - 'Kira': 'kira.md'
  - 'Culture & Tools':
    - 'Culture': 'tools/culture.md' 
    - 'Agility': 'tools/agility.md'
    - 'Container & Orchestration': 'tools/containers.md'
    - 'Hacking': 'tools/hacking.md'
    - 'Machine learning': 'tools/machinelearning.md'
    - 'Microsoft': 'tools/microsoft.md'
    - 'No code': 'tools/nocode.md'
    - 'Presentation': 'tools/presentation.md'
    - 'Testing': 'tools/testing.md'
    - 'Website': 'tools/website.md'
  - 'Agility': 
    - 'Jira': 'jira/workflows.md'
  - 'Git': 
    - 'Learn': 'git/learn.md'
    - 'Useful': 'git/git.md'
  - 'Container & Orchestration':
    - 'Setup': 'docker/setup.md'
    - 'Debug': 'docker/debug.md'
    - 'CLI': 'docker/command.md'
    - 'docker-compose': 'docker/compose.md'
    - 'Dockerfile': 'docker/dockerfile.md'
    - 'Template': 'docker/template.md'
    - 'Kubernetes': 'kubernetes/kubernetes.md'
  - 'CI/CD':
    - 'Jenkins':
      - 'Jenkinsfile': 'jenkins/jenkinsfile.md'
      - 'Libs': 'jenkins/lib.md'
    - 'Azure DevOps': 'azure/devops.md'
  - 'Dev':
    - 'es6': 'javascript/es6.md'
  - 'Ops':
    - 'Bash':
      - 'Scripting': 'bash/scripting.md'
      - 'Shortcuts': 'bash/command_line_shortcut.md'
    - 'Crontab': 'system/cron.md'
    - 'Fedora':
      - 'Fix': 'fedora/fix.md'
      - 'Setup': 'fedora/setup.md'
      - 'System & Network': 'fedora/sysnet.md'
    - 'Network': 'network/network.md'
    - 'Pass': 'system/passwordstore.md'
    - 'Postgres': 'database/postgres.md'
    - 'Python': 'python/python.md'
    - 'System': 'system/system.md'
    - 'tcpdump': 'network/tcpdump.md'
  - 'Cloud':
    - 'Azure CLI': 'azure/azure.md'
    - 'Terraform': 'azure/terraform.md'
  - 'Interview':
    - 'Question': 'interview/personal.md'
    - 'System Administration': 'interview/sysadmin.md'
  - 'Vim':
    - 'Useful': 'vim/vim.md'
    - 'IDE': 'vim/ide.md'
    - 'Cheatsheet': 'vim/cheatsheet.md'
